//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodPressureInformations
    {
        public int BloodPressureInformationID { get; set; }
        public Nullable<System.DateTime> MeasurementTimeBloodPressure { get; set; }
        public int SystolicPressure { get; set; }
        public int DiastolicPressure { get; set; }
        public string BodyPosition { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
