//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodInformations
    {
        public int FoodInformationID { get; set; }
        public Nullable<System.DateTime> MealTime { get; set; }
        public string Intake { get; set; }
        public string FoodProduct { get; set; }
        public decimal AmountOfCalories { get; set; }
        public Nullable<decimal> AmountOfCarbohydrates { get; set; }
        public Nullable<decimal> AmountOfProtein { get; set; }
        public Nullable<decimal> AmountOfSugar { get; set; }
        public Nullable<decimal> AmountOfFat { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
