//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meals
    {
        public int MealID { get; set; }
        public int UserID { get; set; }
        public int FoodInformationID { get; set; }
        public int WaterInformationID { get; set; }
    
        public virtual FoodInformations FoodInformations { get; set; }
        public virtual Users Users { get; set; }
        public virtual WaterInformations WaterInformations { get; set; }
    }
}
