//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SleepModes
    {
        public int SleepModeID { get; set; }
        public int UserID { get; set; }
        public int SleepInformationID { get; set; }
    
        public virtual SleepInformations SleepInformations { get; set; }
        public virtual Users Users { get; set; }
    }
}
