//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSigns
    {
        public int VitalSignID { get; set; }
        public int UserID { get; set; }
        public int TemperatureInformationID { get; set; }
        public int PulseInformationID { get; set; }
        public int BloodPressureInformationID { get; set; }
    
        public virtual BloodPressureInformations BloodPressureInformations { get; set; }
        public virtual PulseInformations PulseInformations { get; set; }
        public virtual TemperatureInformations TemperatureInformations { get; set; }
        public virtual Users Users { get; set; }
    }
}
