//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTracker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterInformations
    {
        public int WaterInformationID { get; set; }
        public Nullable<System.DateTime> DrinkingTime { get; set; }
        public decimal LiquidLevel { get; set; }
        public string LiquidType { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
